### ISSUE TITLE
Color incorrect on item type 

### ISSUE THREAD

**Issue by StrongmanIX** [DmitrijsNau/raindle#10]
Hey the Rejuv Rack should have been yellow instead of red on the "item type" according to the "item type" category when hovered over.
Below i have included the screen shots of the error
![Tmp2](https://github.com/user-attachments/assets/507514c7-e89c-451d-9ca3-5a615135e3dd)

![Tmp2](https://github.com/user-attachments/assets/6bdce9cb-c7d8-4e33-8d59-fdc8a0fa30de)

**Comment by DmitrijsNau** [comment]
Hey, thanks for pointing this out. I went ahead and fixed the issue, thanks for playing after all this time! ❤️
