### ISSUE TITLE
App runs on system time

### ISSUE THREAD

**Issue by RuntyFlame53268** [DmitrijsNau/raindle#3]
the application runs based off of the user's system time, instead of a coordinated time
meaning 2 people can have different correct answers

**Comment by DmitrijsNau** [comment]
https://stackoverflow.com/questions/24202641/how-can-you-get-the-server-time-from-firebase
leaving this for myself here, I'll try to get to this this weekend

**Comment by DmitrijsNau** [comment]
fixed with new changes today! Thank you for your input :)
