### ISSUE TITLE
Item cooldowns incorrect

### ISSUE THREAD

**Issue by MerlinDaWizard** [DmitrijsNau/raindle#4]
A few items such as:
- Unstable Tesla Coil
- Shuriken
- Runald's Band
- Kjaro's Band
- Hooks of Heresy
- H3AD-5T v2
- Essence of Heresy

Have an invalid value for their cooldown of `1-10 seconds`. Which would instead should be classified as `.1-10 seconds` or added as its own category.
Otherwise, when calculating if a guess is correct. The `values.indexOf("1-10 seconds") = -1` which results in false negatives on close guesses / correct guesses.
<details>
  <summary>Example below (Spoiler for answer 2024/05/24)</summary>

  ![examples](https://github.com/DmitrijsNau/raindle/assets/47361765/b8ac17bd-34f6-4151-a799-a1b015b90ed5)

</details>

**Comment by DmitrijsNau** [comment]
You're actually the GOAT for going through and finding this, I'll fix it tonight when I get home!

**Comment by DmitrijsNau** [comment]
Thanks for pointing this out, should be good now!
